{
  "build": {
    "command": "npm run build",
    "publish": "dist"
  },
  "redirects": [
    {
      "from": "/api/*",
      "to": "https://cinemaguide.skillbox.cc/:splat",
      "status": 200,
      "force": true
    },
    {
      "from": "/*",
      "to": "/index.html",
      "status": 200
    }
  ],
  "headers": [
    {
      "for": "/*",
      "values": {
        "X-Content-Type-Options": "nosniff",
        "X-Frame-Options": "DENY",
        "X-XSS-Protection": "1; mode=block",
        "Cache-Control": "public, max-age=31536000, immutable"
      }
    }
  ]
}
